# Generated by Django 4.2.7 on 2023-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_image/', verbose_name='Original Image')),
                ('edited_image', models.ImageField(blank=True, null=True, upload_to='edited_image/', verbose_name='Edited Image')),
                ('uuid', models.CharField(max_length=15, verbose_name='Uuid')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Result')),
            ],
        ),
    ]
